"""add carrier_name to parcel

Revision ID: 18eaded18684
Revises: b4081bbbadc8
Create Date: 2026-10-01 09:41:32.627150

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18eaded18684"
down_revision: Union[str, Sequence[str], None] = "b4081bbbadc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parcels", sa.Column("carrier_name", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parcels", "carrier_name")
    # ### end Alembic commands ###
