"""fix session id type

Revision ID: b4081bbbadc8
Revises: 6c98e9335d7d
Create Date: 2026-09-28 17:39:07.459353

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4081bbbadc8"
down_revision: Union[str, Sequence[str], None] = "6c98e9335d7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parcels",
        "session_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parcels",
        "session_id",
        existing_type=sa.String(length=36),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
